import React, { createContext, useContext, useState } from "react";

const DataContext = createContext(undefined);

const initialVehicleSalesData = {
  "Dec 2025": [
    {
      team: "NSR1 – Mike",
      avatar: "M",
      Kicks: 5,
      E26: 2,
      N18: 3,
      Patrol: 1,
      D23: 4,
      Terra: 2,
      Livina: 1,
      NissanZ: 0,
      Prem: 1,
    },
    {
      team: "NSR2 – Jhoven",
      avatar: "J",
      Kicks: 4,
      E26: 3,
      N18: 2,
      Patrol: 0,
      D23: 3,
      Terra: 1,
      Livina: 2,
      NissanZ: 1,
      Prem: 0,
    },
    {
      team: "NSR3 – Jayr",
      avatar: "JR",
      Kicks: 3,
      E26: 1,
      N18: 1,
      Patrol: 1,
      D23: 2,
      Terra: 2,
      Livina: 0,
      NissanZ: 0,
      Prem: 0,
    },
  ],
  "Jan 2026": [
    {
      team: "NSR1 – Mike",
      avatar: "M",
      Kicks: 6,
      E26: 3,
      N18: 4,
      Patrol: 2,
      D23: 5,
      Terra: 3,
      Livina: 2,
      NissanZ: 1,
      Prem: 2,
    },
    {
      team: "NSR2 – Jhoven",
      avatar: "J",
      Kicks: 5,
      E26: 4,
      N18: 3,
      Patrol: 1,
      D23: 4,
      Terra: 2,
      Livina: 3,
      NissanZ: 2,
      Prem: 1,
    },
    {
      team: "NSR3 – Jayr",
      avatar: "JR",
      Kicks: 4,
      E26: 2,
      N18: 2,
      Patrol: 2,
      D23: 3,
      Terra: 3,
      Livina: 1,
      NissanZ: 1,
      Prem: 1,
    },
  ],
  "Feb 2026": [
    {
      team: "NSR1 – Mike",
      avatar: "M",
      Kicks: 7,
      E26: 4,
      N18: 5,
      Patrol: 3,
      D23: 6,
      Terra: 4,
      Livina: 3,
      NissanZ: 2,
      Prem: 3,
    },
    {
      team: "NSR2 – Jhoven",
      avatar: "J",
      Kicks: 6,
      E26: 5,
      N18: 4,
      Patrol: 2,
      D23: 5,
      Terra: 3,
      Livina: 4,
      NissanZ: 3,
      Prem: 2,
    },
    {
      team: "NSR3 – Jayr",
      avatar: "JR",
      Kicks: 5,
      E26: 3,
      N18: 3,
      Patrol: 3,
      D23: 4,
      Terra: 4,
      Livina: 2,
      NissanZ: 2,
      Prem: 2,
    },
  ],
  "Mar 2026": [],
  "Apr 2026": [],
  "May 2026": [],
  "Jun 2026": [],
  "Jul 2026": [],
  "Aug 2026": [],
  "Sep 2026": [],
  "Oct 2026": [],
  "Nov 2026": [],
  "Dec 2026": [],
};

const initialApplicationData = {
  "Dec 2025": [
    {
      team: "NSR1 – Mike",
      avatar: "M",
      applications: 25,
      approvedAsApplied: 18,
      approvedNotAsApplied: 4,
      availed: 16,
    },
    {
      team: "NSR2 – Jhoven",
      avatar: "J",
      applications: 20,
      approvedAsApplied: 15,
      approvedNotAsApplied: 3,
      availed: 13,
    },
    {
      team: "NSR3 – Jayr",
      avatar: "JR",
      applications: 15,
      approvedAsApplied: 7,
      approvedNotAsApplied: 3,
      availed: 6,
    },
  ],
  "Jan 2026": [
    {
      team: "NSR1 – Mike",
      avatar: "M",
      applications: 23,
      approvedAsApplied: 16,
      approvedNotAsApplied: 3,
      availed: 14,
    },
    {
      team: "NSR2 – Jhoven",
      avatar: "J",
      applications: 18,
      approvedAsApplied: 14,
      approvedNotAsApplied: 3,
      availed: 12,
    },
    {
      team: "NSR3 – Jayr",
      avatar: "JR",
      applications: 14,
      approvedAsApplied: 8,
      approvedNotAsApplied: 2,
      availed: 7,
    },
  ],
  "Feb 2026": [
    {
      team: "NSR1 – Mike",
      avatar: "M",
      applications: 21,
      approvedAsApplied: 15,
      approvedNotAsApplied: 3,
      availed: 13,
    },
    {
      team: "NSR2 – Jhoven",
      avatar: "J",
      applications: 17,
      approvedAsApplied: 13,
      approvedNotAsApplied: 2,
      availed: 11,
    },
    {
      team: "NSR3 – Jayr",
      avatar: "JR",
      applications: 12,
      approvedAsApplied: 7,
      approvedNotAsApplied: 2,
      availed: 6,
    },
  ],
  "Mar 2026": [],
  "Apr 2026": [],
  "May 2026": [],
  "Jun 2026": [],
  "Jul 2026": [],
  "Aug 2026": [],
  "Sep 2026": [],
  "Oct 2026": [],
  "Nov 2026": [],
  "Dec 2026": [],
};

const initialApplicationsMatrix = {
  "Dec 2025": {
    applied: 60,
    approvedAsApplied: 40,
    approvedNotAsApplied: 10,
    availed: 35,
  },
  "Jan 2026": {
    applied: 55,
    approvedAsApplied: 38,
    approvedNotAsApplied: 8,
    availed: 30,
  },
  "Feb 2026": {
    applied: 50,
    approvedAsApplied: 35,
    approvedNotAsApplied: 7,
    availed: 28,
  },
  "Mar 2026": {},
  "Apr 2026": {},
  "May 2026": {},
  "Jun 2026": {},
  "Jul 2026": {},
  "Aug 2026": {},
  "Sep 2026": {},
  "Oct 2026": {},
  "Nov 2026": {},
  "Dec 2026": {},
};

const initialVehicleSalesByModel = {
  "Dec 2025": {
    Kicks: 12,
    E26: 6,
    N18: 6,
    Patrol: 2,
    D23: 9,
    Terra: 5,
    Livina: 3,
    "Nissan Z": 1,
    Prem: 1,
  },
  "Jan 2026": {
    Kicks: 15,
    E26: 9,
    N18: 9,
    Patrol: 5,
    D23: 12,
    Terra: 8,
    Livina: 6,
    "Nissan Z": 4,
    Prem: 4,
  },
  "Feb 2026": {
    Kicks: 18,
    E26: 12,
    N18: 12,
    Patrol: 8,
    D23: 15,
    Terra: 11,
    Livina: 9,
    "Nissan Z": 7,
    Prem: 7,
  },
  "Mar 2026": {
    Kicks: 14,
    E26: 8,
    N18: 8,
    Patrol: 4,
    D23: 11,
    Terra: 7,
    Livina: 5,
    "Nissan Z": 3,
    Prem: 3,
  },
  "Apr 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "May 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Jun 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Jul 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Aug 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Sep 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Oct 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Nov 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
  "Dec 2026": {
    Kicks: 0,
    E26: 0,
    N18: 0,
    Patrol: 0,
    D23: 0,
    Terra: 0,
    Livina: 0,
    "Nissan Z": 0,
    Prem: 0,
  },
};

const initialPaymentTermData = {
  "Dec 2025": { Cash: 15, Financing: 30, BankPO: 10 },
  "Jan 2026": { Cash: 18, Financing: 35, BankPO: 12 },
  "Feb 2026": { Cash: 22, Financing: 42, BankPO: 15 },
  "Mar 2026": { Cash: 17, Financing: 33, BankPO: 11 },
  "Apr 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "May 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Jun 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Jul 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Aug 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Sep 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Oct 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Nov 2026": { Cash: 0, Financing: 0, BankPO: 0 },
  "Dec 2026": { Cash: 0, Financing: 0, BankPO: 0 },
};

const initialReservationByTeam = {
  "Dec 2025": { "NSR1 – Mike": 35, "NSR2 – Jhoven": 32, "NSR3 – Jayr": 25 },
  "Jan 2026": { "NSR1 – Mike": 38, "NSR2 – Jhoven": 35, "NSR3 – Jayr": 28 },
  "Feb 2026": { "NSR1 – Mike": 42, "NSR2 – Jhoven": 38, "NSR3 – Jayr": 32 },
  "Mar 2026": { "NSR1 – Mike": 36, "NSR2 – Jhoven": 33, "NSR3 – Jayr": 27 },
  "Apr 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "May 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Jun 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Jul 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Aug 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Sep 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Oct 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Nov 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
  "Dec 2026": { "NSR1 – Mike": 0, "NSR2 – Jhoven": 0, "NSR3 – Jayr": 0 },
};

export const DataProvider = ({ children }) => {
  const [selectedYear, setSelectedYear] = useState("2026");
  const [selectedMonth, setSelectedMonth] = useState("Feb 2026");
  const [vehicleSalesData, setVehicleSalesData] = useState(
    initialVehicleSalesData,
  );
  const [applicationData, setApplicationData] = useState(
    initialApplicationData,
  );
  const [applicationsMatrix, setApplicationsMatrix] = useState(
    initialApplicationsMatrix,
  );
  const [vehicleSalesByModel, setVehicleSalesByModel] = useState(
    initialVehicleSalesByModel,
  );
  const [paymentTermData, setPaymentTermData] = useState(
    initialPaymentTermData,
  );
  const [reservationByTeam, setReservationByTeam] = useState(
    initialReservationByTeam,
  );

  return (
    <DataContext.Provider
      value={{
        selectedYear,
        setSelectedYear,
        selectedMonth,
        setSelectedMonth,
        vehicleSalesData,
        setVehicleSalesData,
        applicationData,
        setApplicationData,
        applicationsMatrix,
        setApplicationsMatrix,
        vehicleSalesByModel,
        setVehicleSalesByModel,
        paymentTermData,
        setPaymentTermData,
        reservationByTeam,
        setReservationByTeam,
      }}
    >
      {children}
    </DataContext.Provider>
  );
};

export const useData = () => {
  const context = useContext(DataContext);
  if (context === undefined) {
    throw new Error("useData must be used within a DataProvider");
  }
  return context;
};
